version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - public
      - admin

  public:
    build:
      context: .
      dockerfile: public.Dockerfile

  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      PORT: 80
      DB_HOST: postgresql
      DB_USER: ${FOOD_FINDER_POSTGRES_USER}
      DB_PASSWORD: ${FOOD_FINDER_POSTGRES_PASSWORD}
      DB_NAME: ${FOOD_FINDER_POSTGRES_DB}
    depends_on:
      - postgresql

  data:
    build:
      context: .
      dockerfile: data.Dockerfile
    environment:
      SQL_USER: ${FOOD_FINDER_POSTGRES_USER}
      SQL_PASSWORD: ${FOOD_FINDER_POSTGRES_PASSWORD}
      SQL_DB: ${FOOD_FINDER_POSTGRES_DB}
      SQL_HOST: "postgresql:5432"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${FOOD_FINDER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FOOD_FINDER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${FOOD_FINDER_POSTGRES_DB}
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
