name: data

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

  merge_group:
    branches: [ main ]

jobs:
  data-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install poetry & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry --version
        poetry config settings.virtualenvs.in-project true
        poetry install -vv -C ./data -n
    
    - name: Black formatting check
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./data"

    - name: Pylint check
      run: |
        pylint $(git ls-files './data/*.py')

    - name: Mypy check
      run: |
        MYPYPATH=./server mypy --strict ./data
