name: data

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

  merge_group:
    branches: [ main ]

jobs:
  data-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install poetry & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry --version
        poetry install -vv -C ./data -n
    
    - name: Black formatting check
      run: |
        poetry run -C ./data black --check --verbose ./data

    - name: Pylint check
      run: |
        poetry run -C ./data pylint $(git ls-files './data/*.py')

    - name: Mypy check
      run: |
        MYPYPATH=./server yes | poetry run -C ./data mypy --install-types
        MYPYPATH=./server poetry run -C ./data mypy --strict ./data
