name: server

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

  merge_group:
      branches: [ main ]
  
jobs:
  server-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      
    - name: Install dependencies
      working-directory: server
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install -r requirements.txt

    - name: Lint
      working-directory: server
      run: black .

    # - name: Test
    #   working-directory: server
    #   run: strawberry server schema
