name: server

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

  merge_group:
      branches: [ main ]
  
jobs:
  server-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      
    - name: Install poetry & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry --version
        poetry config virtualenvs.in-project true
        poetry install -vv -C ./server -n
  
    - name: Black formatting check
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./server"

    - name: Pylint check
      run: |
        pylint $(git ls-files './server/*.py')

    - name: Mypy check
      run: |
        MYPYPATH=./data mypy --strict ./server

      # - name: Test
      #   working-directory: server
      #   run: strawberry server schema
